# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dygn < Formula
  desc "A CLI tool to produce an IPv6 address with the host portion being a modified EUI-64."
  homepage "https://github.com/ttl256/dygn"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ttl256/dygn/releases/download/v1.0.4/dygn_Darwin_arm64.tar.gz"
      sha256 "ace1b8dd6c6165cbe986699696158b9e7627a3a8b1ff3150f61df71ac58eb80c"

      def install
        bin.install "dygn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ttl256/dygn/releases/download/v1.0.4/dygn_Darwin_x86_64.tar.gz"
      sha256 "099fcebed92624b1d5cbf20e09a0bd84dc8e5d5c5205643b798f7b25572eba83"

      def install
        bin.install "dygn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ttl256/dygn/releases/download/v1.0.4/dygn_Linux_arm64.tar.gz"
      sha256 "895d51b8aa28756a54da2b6c8128231093fa3f3cf5c1288c0cade1659be30356"

      def install
        bin.install "dygn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ttl256/dygn/releases/download/v1.0.4/dygn_Linux_x86_64.tar.gz"
      sha256 "31a2eb050d2506e64564cbac0b4e19853c396c07af53ef3355ce36e33fdbc1a1"

      def install
        bin.install "dygn"
      end
    end
  end
end
